### PR TITLE
remove duplicate NFTs via group by

### PR DESCRIPTION
**Pull request by dandlezzz**

### CODE REVIEW

**Comment by kespinola** [comment]
Screen Shot 2022-03-04 at 5 18 19 AM
Most of the dups ae gone but still have a few.

**Comment by dandlezzz** [comment]
@kespinola what’s the query ?

**Comment by dandlezzz** [comment]
Example gql query gone wrong
```
query {
  nfts(creators: [
    "FxR1KHfFa5LrJ467HdziVRW2LUu6rrgHq78WMCZsF8dG"
  ]
    attributes: [{
      traitType: "Skin",
      values: ["Gray"]
    },
     {
            traitType: "Hat",
            values: ["Bear OG"]
          },
    ]
   
   
  ) {
    name,
    address
    attributes {
      traitType
      value
    }
  }
}
```

**Comment by kespinola** [comment]
handled here. https://github.com/holaplex/solana-indexer/pull/199

**Pull request closed without merging**
